### ISSUE TITLE
Enable Auto-changelog on different branches

### ISSUE THREAD

**Issue by kturung** [Michael-F-Bryan/auto-changelog#31]
First of all, thank you for this amazing app. I've tried using auto-changelog on other branches but It got failed. Is there a way to run this app for other branches rather than Master.

Best Regards

**Comment by WqyJh** [comment]
See https://github.com/Michael-F-Bryan/auto-changelog/pull/29
Maybe in the next version, you can do this:
```bash
auto-changelog --stopping-commit <branch> # default `HEAD`
```

**Comment by KeNaCo** [comment]
As @WqyJh said and implemented(:+1: :1st_place_medal: ).

In current state its kinda inconvenient to work with auto-changelog, due to massive rewrite. 
My plan is to implement predefined features(but we can discuss if earlier release with just some subset will be a better option) and then I need to discuss with @Michael-F-Bryan as he is the owner of PyPI account.

**Comment by Michael-F-Bryan** [comment]
@KeNaCo, do you have a PyPI account? Let me know your username and I'll transfer ownership to you.

**Comment by KeNaCo** [comment]
@Michael-F-Bryan https://pypi.org/user/KeNaCo/

**Comment by Michael-F-Bryan** [comment]
@KeNaCo I've made you an owner on PyPI.

**Comment by KeNaCo** [comment]
0.3.0 released 🎉
